Provider: Yaml

dictionary:
  # LV1 SPONGE
  - id: 19
    delay: 500
    blocks:
      # NATURAL DEFAULT
      # stone-1
      - id: 1
        meta: 0
        percentage: 100
        factor: 0.7
      # dirt
      - id: 3
        meta: 0
        percentage: 60
        factor: 0.7
      # sand-1
      - id: 12
        meta: 0
        percentage: 10
        factor: 0.7

      # NATURAL ENTITY
      # wood-1
      - id: 17
        meta: 0
        percentage: 15
        factor: 0.7

      # ORE
      # coal
      - id: 16
        meta: 0
        percentage: 15
        factor: 0.9
      # iron
      - id: 15
        meta: 0
        percentage: 3
        factor: 1.2

  # LV2 NETHER RACK
  - id: 87
    delay: 1000
    blocks:
      # NATURAL DEFAULT
      # stone-2
      - id: 1
        meta: 1
        percentage: 10
        factor: 0.7
      # stone-3
      - id: 1
        meta: 3
        percentage: 10
        factor: 0.7
      # stone-4
      - id: 1
        meta: 5
        percentage: 10
        factor: 0.7
      # gravel
      - id: 13
        meta: 0
        percentage: 10
        factor: 0.7
      # sand-2
      - id: 12
        meta: 1
        percentage: 2
        factor: 0.7
      # sandstone
      - id: 24
        meta: 0
        percentage: 5
        factor: 0.7

      # NATURAL ENTITY
      # wood-2
      - id: 17
        meta: 1
        percentage: 8
        factor: 0.7
      # wood-3
      - id: 17
        meta: 2
        percentage: 8
        factor: 0.7
      # wood-4
      - id: 17
        meta: 3
        percentage: 8
        factor: 0.7

      # ORE
      # gold
      - id: 14
        meta: 0
        percentage: 1
        factor: 1.5

  # LV3 SOUL SAND
  - id: 88
    delay: 2000
    blocks:
      # NATURAL ADVANCED
      # ice
      - id: 79
        meta: 0
        percentage: 0.1
        factor: 1
      # obsidian
      - id: 49
        meta: 0
        percentage: 0.1
        factor: 1

      # NATURAL ENTITY
      # wood-5
      - id: 162
        meta: 0
        percentage: 8
        factor: 0.5
      # wood-6
      - id: 162
        meta: 1
        percentage: 8
        factor: 0.5
      # wool
      - id: 35
        meta: 0
        percentage: 5
        factor: 1.2

      # NATURAL ENTITY ADVANCED
      # pumpkin
      - id: 86
        meta: 0
        percentage: 1
        factor: 1
      # water melon
      - id: 103
        meta: 0
        percentage: 1
        factor: 1

      # ORE
      # redstone
      - id: 73
        meta: 0
        percentage: 0.2
        factor: 1.5
      # lazuli
      - id: 21
        meta: 0
        percentage: 0.2
        factor: 1.5
      # diamond
      - id: 56
        meta: 0
        percentage: 0.2
        factor: 2

  # LV4 NETHER WART BLOCK
  - id: 214
    delay: 4000
    blocks:
      # NATURAL ADVANCED
      # clay
      - id: 82
        meta: 0
        percentage: 5
        factor: 1.2
      # glowstone
      - id: 89
        meta: 0
        percentage: 1
        factor: 1.5
      # sea lantern
      - id: 169
        meta: 0
        percentage: 0.1
        factor: 1.5

      # NETHER
      # quartz
      - id: 153
        meta: 0
        percentage: 3
        factor: 1.2

  # LV5 END STONE BRICKS
  - id: 206
    delay: 8000
    blocks:
      # NATURAL ADVANCED
      # shullker chest
      - id: 205
        meta: 0
        percentage: 0.1
        factor: 1
      # slim block
      - id: 165
        meta: 0
        percentage: 0.05
        factor: 1

      # ORE
      # emerald
      - id: 129
        meta: 0
        percentage: 0.1
        factor: 1