Provider: Yaml


# =================
# Database settings
# =================


db:
  type: "Mysql"
  sqlite:
    db-file: "user-info.sqlite3"
  mysql:
    host: "localhost"
    port: 3306
    user: "root"
    password: "your-password-here"


# =================
# User Group settings
# =================


category:
  user:
    id: 0
    display-name: "<§2[유저]§f %name>"
    nametag: "§7<<§l§f%name§r§7>>"
  staff:
    id: 10
    display-name: "<§b[Staff]§f %name>"
    nametag: "§7<<§l§b%name§r§7>>"


# =================
# Skyblock settings
# =================


skyblock:
  distance: 16
  default-island-shape: [[[0, 0, 31, 37, 0, 0], [0, 31, 0, 31, 31, 0], [31, 31, 0, 37, 0, 0], [0, 0, 31, 0, 31, 0], [0, 0, 38, 0, 31, 0], [0, 0, 0, 31, 0, 0]],
                         [[0, 0, 2, 2, 0, 0], [0, 2, 2, 2, 2, 0], [2, 2, 2, 2, 2, 2], [2, 2, 2, 2, 2, 2], [0, 2, 2, 2, 2, 0], [0, 0, 2, 2, 0, 0]],
                         [[0, 0, 1, 1, 0, 0], [0, 1, 1, 1, 1, 0], [1, 1, 7, 7, 1, 1], [1, 1, 7, 7, 1, 1], [0, 1, 1, 1, 1, 0], [0, 0, 1, 1, 0, 0]],
                         [[0, 0, 0, 0, 0, 0], [0, 0, 1, 1, 0, 0], [0, 1, 1, 1, 1, 0], [0, 1, 1, 1, 1, 0], [0, 0, 1, 1, 0, 0], [0, 0, 0, 0, 0, 0]],
                         [[0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 1, 1, 0, 0], [0, 0, 1, 1, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0]]]

blockgen:
  levels: 5
  l1:
    id: 19
    meta: 0
    blocks:
      1-0: 0.4
      2-0: 0.4
      17-0: 0.2
  l2:
    id: 168
    meta: 0
    blocks:
      1-0: 0.4
      2-0: 0.4
      17-0: 0.2
  l3:
    id: 168
    meta: 1
    blocks:
      1-0: 0.4
      2-0: 0.4
      17-0: 0.2
  l4:
    id: 168
    meta: 2
    blocks:
      1-0: 0.4
      2-0: 0.4
      17-0: 0.2
  l5:
    id: 201
    meta: 0
    blocks:
      1-0: 0.4
      2-0: 0.4
      17-0: 0.2


default-item-list:
  270-0: 1
  271-0: 1
  269-0: 1
  79-0: 2
  325-10: 1
  351-15: 10
  19-0: 1
  297-0: 64


# =================
# User Interface settings
# =================

prefix:
  info: "<§e안내§f>"
  notice: "<§e공지§f>"

text:
  general:
    guidebook: "§e가이드북"
  skyblock:
    protection-type:
      protection-type: "보호 수준"
      allow-only-owner: "나만"
      allow-invited: "초대된"
      allow-all: "모두"
  blockgen:
    item-tag: "§e생성 블록 §aLV."

message:
  general:
    on-player-join: "§e%player§f 님이 접속했습니다."
    on-player-quit: "§e%player§f 님이 나갔습니다."
    on-player-first-join: "§e%player§f 님이 서버에 처음 접속하셨습니다."
  skyblock:
    teleport-succeed: "§e%player§f 의 구역으로 이동했습니다."
    teleport-succeed-self: "내 구역으로 이동했습니다."
    invite-succeed: "§e%player§f 님을 내 구역으로 초대했습니다."
    invite-received: "§e%owner§f 님의 구역으로 초대되었습니다."
    purge-succeed: "§e%player§f 님을 내 구역에서 추방했습니다."
    protection-type-updated: "내 구역의 보호 수준이 §e%protection-type§f 으로 설정 되었습니다."
  blockgen:
    blockgen-upgrade-succeed: "생성 블록이 §e%level§f 단계로 업그레이드 되었습니다."

popup:
  general:
    on-player-join: "+%player"
    on-player-quit: "-%player"
  skyblock:
    protection-type-warning: "§7이 구역은 §e%protection-type§7 수준으로 보호되고 있습니다."

command:
  management:
    ban-command:
      command: "ban"
      description: "유저를 차단합니다."
      usage: "/b <닉네임>"
      format-error: "/ban <닉네임> <시간> 형식으로 입력해 주시기 바랍니다."
      ban-succeed: "§e%player§f 를 %date 일 동안 차단했습니다."
      ban-failed-playernotfound: "§4%player§f 를 찾을 수 없습니다."
    kick-command:
      command: "k"
      description: "유저를 추방합니다."
      usage: "/k <닉네임>"
      format-error: "/k <닉네임> 형식으로 입력해 주시기 바랍니다."
      kick-succeed: "§e%player§f 를 추방 했습니다."
      kick-failed: "§4%player§f 를 찾을 수 없습니다."
    category-command:
      command: "c"
      description: "유저의 칭호를 바꿉니다."
      usage: "/c <닉네임> <ID>"
      format-error: "/c <닉네임> <ID> 형식으로 입력해 주시기 바랍니다."
      update-succeed: "§e%player 를 분류 ID §e%id:%category-name§f 으로 분류했습니다."
      update-failed-idnotfound: "분류 ID §4%id§f 를 찾을 수 없습니다."
      update-failed-playernotfound: "§4%player§f 를 찾을 수 없습니다."
  skyblock:
    teleport-command:
      command: "이동"
      description: "내 구역 또는 다른 유저의 구역으로 이동합니다."
      usage: "/이동 또는 /이동 <닉네임>"
      teleport-failed-playernotfound: "§4%player§f 님을 찾을 수 없습니다."
    invite-command:
      command: "초대"
      description: "다른 유저를 내 구역으로 초대합니다."
      usage: "/초대 <닉네임>"
      format-error: "/초대 <닉네임> 형식으로 입력해 주시기 바랍니다."
      invite-failed-playeralradyinvited: "§e%player§f 님은 이미 내 구역에 초대되어 있습니다."
      invite-failed-playernotfound: "§4%player§f 님을 찾을 수 없습니다."
    purge-command:
      command: "추방"
      description: "내 구역으로 초대된 유저를 추방합니다."
      usage: "/추방 <닉네임>"
      format-error: "/추방 <닉네임> 형식으로 입력해 주시기 바랍니다."
      purge-failed-playernotfound: "§4%player§f 님을 찾을 수 없습니다."
      purge-failed-playernotinvited: "§4%player§f 님은 초대 목록에 존재하지 않습니다."
    invite-list-command:
      command: "목록"
      description: "내 구역에 초대된 유저 목록을 확인합니다."
      usage: "/목록"
      show-invited-list: "§e%invited-list§f 이 내 구역에 초대되어 있습니다."
      show-invited-list-empty: "아무도 내 구역에 초대되어 있지 않습니다."
    protection-type-command:
      command: "보호"
      description: "내 구역의 보호 수준을 설정합니다."
      usage: "/보호 <나만|초대된|모두>"
      format-error: "/보호 <나만|초대된|모두> 형식으로 입력해 주시기 바랍니다."

guidebook:
  - "§6§lMine24 2021\n§7서버 이용 안내"
  - "p1"
  - "p2"
  - "p3"