Provider: Yaml

database:
  type: "sqlite"
  sqlite:
    db-file: "user-info.db"
  mysql:
    host: "localhost"
    database: "justskyblock"
    port: 3306
    user: "root"
    password: "your-password-here"
