name: Mine2021
main: do1phin.mine2021.ServerAgent
version: "${pom.version}"
api: ["1.0.0"]
author: do1phin
description: 언제 어디서나 즐기는 나만의 세상
website: htttp://Mine24.net
load: STARTUP

permissions:
  mine2021.skyblock:
    description: "스카이블록 이용 권한"
    default: true
  mine2021.management:
    description: "관리 권한"
    default: op