name: JustSkyblock
main: do1phin.mine2021.ServerAgent
version: "${pom.version}"
api: ["1.0.0"]
author: do1phin
description: 언제 어디서나 즐기는 나만의 세상
website: http://skyblock.do1ph.in
load: STARTUP

permissions:
  justskyblock.general:
    description: "서버 이용 권한"
    default: true
  justskyblock.skyblock:
    description: "스카이블록 이용 권한"
    default: true
  justskyblock.management:
    description: "관리 권한"
    default: op