Provider: Yaml

system:
  rule:
    disable-nukkit-commands: true
    enable-inventory-save: true
  ux:
    enable-telepot-to-island: true
    enable-welcome-form: true
    enable-default-items: true
    enable-guidebook: true

crafting:
  additional-recipes:
    - name: "wool2string"
      id: 287
      meta: 0
      amount: 2
      shape: "AAA,ABA,AAA"
      ingredients: "A=0:0,B=35:0"
    - name: "wool2leather"
      id: 334
      meta: 0
      amount: 1
      shape: "AAA,AAA,AAA"
      ingredients: "A=35:0"

    - name: "wheat2sugar-cane"
      id: 338
      meta: 0
      amount: 1
      shape: "AAA,ABA,AAA"
      ingredients: "A=170:0,B=12:0"
    - name: "wheat2bamboo"
      id: -163
      meta: 0
      amount: 1
      shape: "AAA,ABA,AAA"
      ingredients: "A=170:0,B=338:0"
    - name: "wheat2potato"
      id: 392
      meta: 0
      amount: 1
      shape: "AAA,ABA,AAA"
      ingredients: "A=170:0,B=3:1"
    - name: "wheat2carrot"
      id: 391
      meta: 0
      amount: 1
      shape: "AAA,ABA,AAA"
      ingredients: "A=170:0,B=3:0"

    - name: "log2sapling-1"
      id: 6
      meta: 0
      amount: 1
      shape: "ABA,BBB,ABA"
      ingredients: "A=0:0,B=17:0"
    - name: "log2sapling-2"
      id: 6
      meta: 1
      amount: 1
      shape: "ABA,BBB,ABA"
      ingredients: "A=0:0,B=17:1"
    - name: "log2sapling-3"
      id: 6
      meta: 2
      amount: 1
      shape: "ABA,BBB,ABA"
      ingredients: "A=0:0,B=17:2"
    - name: "log2sapling-4"
      id: 6
      meta: 3
      amount: 1
      shape: "ABA,BBB,ABA"
      ingredients: "A=0:0,B=17:3"
    - name: "log2sapling-5"
      id: 6
      meta: 4
      amount: 1
      shape: "ABA,BBB,ABA"
      ingredients: "A=0:0,B=162:0"
    - name: "log2sapling-6"
      id: 6
      meta: 5
      amount: 1
      shape: "ABA,BBB,ABA"
      ingredients: "A=0:0,B=162:1"

  banned-recipes:
    # LV 3 - SOUL TORCH
    - id: -268
      meta: 0
      amount: 4
    # LV 3 - SOUL LANTERN
    - id: -269
      meta: 0
      amount: 1
    # LV 3 - SOUL CAMPFIRE
    - id: 801
      meta: 0
      amount: 1

    # LV 4 - NETHER WART BLOCK
    - id: 214
      meta: 0
      amount: 1

    # LV 5 - END STONE BRICK
    - id: 206
      meta: 0
      amount: 4
    # LV 5 - END STONE BRICK SLAB
    - id: -162
      meta: 0
      amount: 6
    # LV 5 - END STONE BRICK STAIRS
    - id: -178
      meta: 0
      amount: 4
    # LV 5 - END STONE BRICK WALL
    - id: 139
      meta: 10
      amount: 6

default-items:
  - id: 270
    meta: 0
    amount: 1
  - id: 271
    meta: 0
    amount: 1
  - id: 269
    meta: 0
    amount: 1
  - id: 79
    meta: 0
    amount: 2
  - id: 325
    meta: 10
    amount: 1
  - id: 351
    meta: 15
    amount: 10
  - id: 297
    meta: 0
    amount: 64
