Provider: Yaml

skyblock:
  distance: 16
  default-island-shape: [[[0, 0, 31, 37, 0, 0], [0, 31, 0, 31, 31, 0], [31, 31, 0, 37, 0, 0], [0, 0, 31, 0, 31, 0], [0, 0, 38, 0, 31, 0], [0, 0, 0, 31, 0, 0]],
                         [[0, 0, 2, 2, 0, 0], [0, 2, 2, 2, 2, 0], [2, 2, 2, 2, 2, 2], [2, 2, 2, 2, 2, 2], [0, 2, 2, 2, 2, 0], [0, 0, 2, 2, 0, 0]],
                         [[0, 0, 1, 1, 0, 0], [0, 1, 1, 1, 1, 0], [1, 1, 7, 7, 1, 1], [1, 1, 7, 7, 1, 1], [0, 1, 1, 1, 1, 0], [0, 0, 1, 1, 0, 0]],
                         [[0, 0, 0, 0, 0, 0], [0, 0, 1, 1, 0, 0], [0, 1, 1, 1, 1, 0], [0, 1, 1, 1, 1, 0], [0, 0, 1, 1, 0, 0], [0, 0, 0, 0, 0, 0]],
                         [[0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 1, 1, 0, 0], [0, 0, 1, 1, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0]]]
